name: cd
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  test:
    name: Test
    runs-on: ubuntu-18.04
    container:
      # Source: https://github.com/day8/dockerfile-for-dev-ci-image
      image: day8au/dev-ci:0.0.8
    steps:
      - uses: actions/checkout@v2
        with:
          # All of the Git history is required for day8/lein-git-inject to determine the version string.
          fetch-depth: 0
      - name: Maven cache
        uses: actions/cache@v1
        with:
          path: /root/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('project.clj') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - run: lein test
        if: steps.maven-cache.outputs.cache-hit != 'true'
      - run: lein -o test
        if: steps.maven-cache.outputs.cache-hit == 'true'
      - name: Slack notification
        uses: homoluctus/slatify@v2.0.1
        if: failure() || cancelled()
        with:
          type: ${{ job.status  }}
          job_name: lein-git-inject Tests
          channel: '#oss-robots'
          url: ${{ secrets.SLACK_WEBHOOK }}
          commit: true
          token: ${{ secrets.GITHUB_TOKEN }}
  release:
    name: Release
    needs: test
    runs-on: ubuntu-18.04
    container:
      # Source: https://github.com/day8/dockerfile-for-dev-ci-image
      image: day8au/dev-ci:0.0.8
    steps:
      - uses: actions/checkout@v2
        with:
          # All of the Git history is required for day8/lein-git-inject to determine the version string.
          fetch-depth: 0
      - name: Maven cache
        uses: actions/cache@v1
        with:
          path: /root/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('project.clj') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Run lein release
        if: steps.maven-cache.outputs.cache-hit != 'true'
        run: |
          CLOJARS_USERNAME=${{ secrets.CLOJARS_USERNAME }} CLOJARS_PASSWORD=${{ secrets.CLOJARS_PASSWORD }} GITHUB_USERNAME=${{ github.actor }} GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} lein release
      - name: Run lein -o release
        if: steps.maven-cache.outputs.cache-hit == 'true'
        run: |
          CLOJARS_USERNAME=${{ secrets.CLOJARS_USERNAME }} CLOJARS_PASSWORD=${{ secrets.CLOJARS_PASSWORD }} GITHUB_USERNAME=${{ github.actor }} GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} lein -o release
      - name: Slack notification
        uses: homoluctus/slatify@v2.0.1
        if: always()
        with:
          type: ${{ job.status }}
          job_name: lein-git-inject Release
          channel: '#oss-robots'
          url: ${{ secrets.SLACK_WEBHOOK }}
          commit: true
          token: ${{ secrets.GITHUB_TOKEN }}
